### ISSUE TITLE
HTTP Error 403 when trying to retrieve package versions

### ISSUE THREAD

**Issue by fgmacedo** [wuub/requirementstxt#11]
The package versions list isn't displayed, and this error appears on console:

```
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "requirements in /home/fernando/.config/sublime-text-3/Installed Packages/requirementstxt.sublime-package", line 97, in _fetch_packages
  File "./python3.3/urllib/request.py", line 156, in urlopen
  File "./python3.3/urllib/request.py", line 475, in open
  File "./python3.3/urllib/request.py", line 587, in http_response
  File "./python3.3/urllib/request.py", line 513, in error
  File "./python3.3/urllib/request.py", line 447, in _call_chain
  File "./python3.3/urllib/request.py", line 595, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Must access using HTTPS instead of HTTP
```

Sublime Build 3124
requirementstxt v0.3.0

**Comment by wuub** [comment]
On it. 
But the fix will be 3123+ only, I refuse to check anything against ST2 anymore :)

**Comment by wuub** [comment]
0.3.1 should fix the issue for st3 (at least it did on linux).
let me know if it helped, it's been 3 years since I last touched my sublime plugins and I feel a bit rusty

**Comment by fgmacedo** [comment]
Thanks! I'm waiting the new 0.3.1 version appear on PackageControl. Or should I install It from source?

**Comment by wuub** [comment]
Just wait for PackageControl.
